name: validate-codecov-config

on:
  workflow_dispatch:
  pull_request:
    paths: [ codecov.yml ]
  push:
    branches: [ main ]

jobs:
  validate-codecov-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate codecov configuration
        run: curl -sSL --fail-with-body --data-binary @codecov.yml https://codecov.io/validate
